### PR TITLE
set up CI to run tests and build wheels for osx, manylinux1 and windows

### PR DESCRIPTION
**Pull request by anthrotype**
Hello,

I'm using the excellent https://github.com/matthew-brett/multibuild, a set of shell scripts used to build OSX and Linux wheels for the Python scientific stack.
This makes super easy to set up Travis as a Python wheel build farm. (Thanks @matthew-brett!)

I also tried Travis automatic deployment to Github Releases; you can see it working from my fork: https://github.com/anthrotype/pyclipper/releases

@greginvm may want to replace my Github secure `aut_key` with his own, by running the `travis setup releases` command as explained in https://docs.travis-ci.com/user/deployment/releases

BTW, Travis also offers automatic deployment to PyPI, but the latter seems to force you rebuilding the wheel with a regular `bdist_wheel` command running outside our Docker `manylinux1` image. I'm trying to understand if it's possible to upload precompiled artifacts to PyPI using Travis (see https://github.com/travis-ci/dpl/issues/496).

In the meantime, I think it's okay if @greginvm manually uploads to PyPI the wheels, by downloading them from the Github releases once Travis has finished uploading them.

This is only the first part. Tomorrow I'll work on adding Windows support via Appveyor -- which also offers automatic deployment to Github releases.

Let me know if you have questions or comments.
Thank you!

Cosimo

### CODE REVIEW

**Comment by anthrotype** [comment]
Ah of course, after merging this, @greginvm needs to activate the `pyclipper` project from his Travis account, in order for the CI to trigger new builds automatically on new pushes or pull requests.

If you are curious, you can read the Travis build logs from my fork at:
https://travis-ci.org/anthrotype/pyclipper/builds

**Comment by anthrotype** [comment]
OK, I also added Windows support through Appveyor!

here's my fork's build status page:
https://ci.appveyor.com/project/anthrotype/pyclipper

And here's how the compiled wheels look like when uploaded to Github:
https://github.com/anthrotype/pyclipper/releases/tag/1.0.2%2Bappveyor

@greginvm when you're happy and merge this, you'll need to activate the repository on both Travis and Appveyor (you can login into both using your Github credentials), and also replace the encrypted OAuth tokens in `.travis.yml` and `.appveyor.yml` with yours.

One little thing to also bear in mind when activating the repo on Appveyor. I decided to call the configuration file `.appveyor.yml` instead of the default `appveyor.yml`, for consistency with Travis, which is also an invisible dot file. However, in order for Appveyor builds to work, you need to go to the project's "Settings", scroll down to "Custom configuration `.yml` file name`, and set that to `.appveyor.yml`, then click "Save".

Let me know if something isn't clear.
Thanks.

**Comment by anthrotype** [comment]
I'm testing only 2.7, 3.4 and 3.5 on both Travis and Appveyor. I decided to drop Python 2.6 as it's too old and I don't think anybody should still use that nowadays.
About 3.3, I'm not sure...
We could add them if you wish (I would prefer to drop them).

**Comment by greginvm** [comment]
Hi @anthrotype , a great PR! :+1: 

About python versions - does Travis support a config in a way to "just do it for all supported versions"? This way the lib wouldn't need updates when a new version of python comes out.

I think 3.x should be supported in full (3.x is supposed to be in "active development", source https://wiki.python.org/moin/Python2orPython3). I see Travis currently supports  3.2 - 3.5. I can add the rest of the versions later, if you want.

I've seen that you included `sympy` as a requirement, which is great!

Otherwise, I haven't finished reviewing yet, I'll finish it in the following days when I have more time.

Oh, and don't forget to add yourself to the authors list :wink:

**Comment by anthrotype** [comment]
> does Travis support a config in a way to "just do it for all supported versions"? This way the lib wouldn't need updates when a new version of python comes out.

The thing is, we can't simpy use Travis own "python" virtual machines (ie. Ubuntu 12.04 with all python versions installed), because we want to use the PyPA's `manylinux1` docker container (https://github.com/pypa/manylinux) to build wheels that will be compatible with all linux distros. This is why I am using Matthew's `multibuild`, instead of directly using the pythons which comes with Travis.
So yes, for future versions of Python we will need to update the lib.

I'll add 3.3, but 3.2 is not installed in the manylinux1 docker so I think that's no longer supported for this purposes.

**Comment by anthrotype** [comment]
but if you want, we can simply run the tests for 3.2, without building a manylinux1 wheel.

**Comment by anthrotype** [comment]
BTW, I don't think all the 3.x are under "active development".

If you read here, https://www.python.org/downloads/release/python-345/

> Python 3.4 has now entered "security fixes only" mode, and as such the only improvements between Python 3.4.4 and Python 3.4.5 are security fixes. Also, Python 3.4.5 has only been released in source code form; no more official binary installers will be produced.

Similarly with 3.3:

https://www.python.org/downloads/release/python-336/

3.2 is even older than that, so the same applies.

**Comment by anthrotype** [comment]
I think we should support only the Pythons which Cython itself supports, which is 2.7, 3.3, 3.4 and 3.5:
https://pypi.python.org/pypi/Cython/

**Comment by greginvm** [comment]
Aha, I understand - supporting only versions that are supported by Cython is the most reasonable. Thanks!

**Comment by anthrotype** [comment]
Thanks for merging this!
Just curious, why do the commits look like squashed into a single one?

**Comment by greginvm** [comment]
Because they are - squash and merge option on Github. Lately I've been using this for larger PRs so that its easier to follow when a feature was actually added to master.

**Comment by anthrotype** [comment]
Well, if you prefer like that, that's fine.
I take great care making my commits granular and one per file basis, to make it easier to trace the history of changes. Never mind, thanks again!

**Pull request merged**
